server:
  port: 9000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///D:/U/Tecnologia/2024-1/ProfundizaciónSoftware/configs-multi-project-trabajo-final/configs-multi-project-trabajo-final
  security:
    user:
      name: ${CONFIG_NAME}
      password: ${CONFIG_PASSWORD}
